# Generated by Django 3.2.3 on 2021-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classroom_student_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='status_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Archived')], default=1),
        ),
    ]
