# Generated by Django 3.2.3 on 2021-05-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classroom_status_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='status_type',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status_type',
            new_name='status',
        ),
    ]
