# Generated by Django 3.2.3 on 2021-06-08 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210530_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 8, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 8, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 8, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
