# Generated by Django 3.2.3 on 2021-06-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210608_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='max_starts',
            new_name='max_stars',
        ),
    ]
