# Generated by Django 3.2.4 on 2022-01-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_submissionstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='student_indexes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='submissionstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'Working on it'), (2, 'Stuck')], default=0),
        ),
    ]
