# Generated by Django 3.2.4 on 2022-04-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_announcement_resource_resourcesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
