# Generated by Django 3.2.4 on 2022-07-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_task_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionstatus',
            options={'verbose_name_plural': 'SubmissionStatuses'},
        ),
        migrations.AddField(
            model_name='task',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
