# Generated by Django 3.2.4 on 2023-05-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_enroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enroll',
        ),
    ]
