# Generated by Django 3.2.4 on 2023-07-11 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_delete_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GroupSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('associated_students', models.ManyToManyField(related_name='associated_group_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitting_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_group_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='group_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.groupsubmission'),
        ),
    ]
