# Generated by Django 3.2.4 on 2023-07-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='group_indexes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='is_group_task',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveSmallIntegerField()),
                ('member_indexes', models.JSONField(default=list)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(fields=('classroom', 'group_number'), name='unique_identifier'),
        ),
    ]
