# Generated by Django 3.2.4 on 2023-07-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230711_0632'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE core_classroom DROP COLUMN IF EXISTS group_indexes;')
    ]
