# Generated by Django 3.2.4 on 2023-07-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230703_0253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGroup',
        ),
    ]
