# Generated by Django 3.2.4 on 2023-07-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230711_0811'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE core_task DROP COLUMN IF EXISTS is_group_task;'),
        migrations.RunSQL('DROP TABLE IF EXISTS core_groupsubmission_associated_students;'),
        
    ]
