# Generated by Django 3.2.4 on 2023-07-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230711_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsubmission',
            name='associated_students',
        ),
    ]
