# Generated by Django 3.2.4 on 2023-07-12 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_remove_groupsubmission_associated_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubmission',
            name='associated_students',
            field=models.ManyToManyField(related_name='associated_group_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
