# Generated by Django 3.2.4 on 2023-07-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_groupsubmission_associated_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsubmission',
            name='associated_students',
        ),
        migrations.RemoveField(
            model_name='groupsubmission',
            name='submitting_student',
        ),
        migrations.RemoveField(
            model_name='groupsubmission',
            name='task',
        ),
    ]
