# Generated by Django 3.2.4 on 2023-07-12 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_auto_20230712_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='group_submission',
        ),
        migrations.AddField(
            model_name='groupsubmission',
            name='associated_students',
            field=models.ManyToManyField(blank=True, null=True, related_name='associated_group_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupsubmission',
            name='submitting_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_group_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupsubmission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AlterField(
            model_name='groupsubmission',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
