# Generated by Django 3.2.4 on 2023-07-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20230712_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupSubmission',
        ),
    ]
