# Generated by Django 3.2.3 on 2021-05-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_class_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
