# Generated by Django 3.2.3 on 2021-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_class_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_class_code', models.CharField(max_length=6)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_class_code',
        ),
    ]
