# Generated by Django 3.2.4 on 2021-08-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
