# Generated by Django 3.2.4 on 2022-01-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='created_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
