# Generated by Django 4.2.1 on 2023-05-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentprofile_created_by_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'temporaryStudentAccount'), (2, 'teacher'), (3, 'student')]),
        ),
    ]
