# Generated by Django 3.2.4 on 2023-05-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'temporaryStudentAccount'), (2, 'teacher'), (3, 'student')], default=2),
        ),
    ]
