# Generated by Django 3.2.4 on 2023-06-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentUserID', models.IntegerField()),
                ('classroom', models.CharField(max_length=6)),
                ('studentIndex', models.IntegerField()),
            ],
        ),
    ]
