# Generated by Django 3.2.4 on 2023-06-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_enroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enroll',
        ),
    ]
