# Generated by Django 3.2.4 on 2023-07-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20230627_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher')], default=2),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
